In [1]:
#Loading scikit's random forest classifier library
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
#loading Pandas
import pandas as pd
#Loading numpy
import numpy as np
#Setting random seed
np.random.seed(0)

In [2]:
CBS_2011_Hr=pd.read_csv("CBS_2011_TotalHr.csv")
CBS_2011_Hr.head()

Unnamed: 0  instant  season  mnth  hr  holiday  weekday  workingday  \
0           0        1       1     1   0        0        6           0   
1           1        2       1     1   1        0        6           0   
2           2        3       1     1   2        0        6           0   
3           3        4       1     1   3        0        6           0   
4           4        5       1     1   4        0        6           0   

   weathersit  temp   atemp   hum  windspeed  BusiestSta  
0           1  0.24  0.2879  0.81        0.0       31007  
1           1  0.22  0.2727  0.80        0.0       31104  
2           1  0.22  0.2727  0.80        0.0       31623  
3           1  0.24  0.2879  0.75        0.0       31102  
4           1  0.24  0.2879  0.75        0.0       31103

In [3]:
del CBS_2011_Hr['Unnamed: 0'] 
del CBS_2011_Hr['instant'] 
# del CBS_2011_Hr['season'] 
# del CBS_2011_Hr['mnth'] 
# del CBS_2011_Hr['hr'] 
# del CBS_2011_Hr['holiday'] 
# del CBS_2011_Hr['weekday'] 
# del CBS_2011_Hr['workingday'] 
del CBS_2011_Hr['weathersit'] 
del CBS_2011_Hr['temp'] 
del CBS_2011_Hr['atemp'] 
del CBS_2011_Hr['hum'] 
del CBS_2011_Hr['windspeed'] 

In [4]:
CBS_2011_Hr.head()

season  mnth  hr  holiday  weekday  workingday  BusiestSta
0       1     1   0        0        6           0       31007
1       1     1   1        0        6           0       31104
2       1     1   2        0        6           0       31623
3       1     1   3        0        6           0       31102
4       1     1   4        0        6           0       31103

In [5]:
#Creating Test and Train Data
CBS_2011_Hr['is_train'] = np.random.uniform(0,1,len(CBS_2011_Hr)) <= .8
#View the top 5 rows
CBS_2011_Hr.head()

season  mnth  hr  holiday  weekday  workingday  BusiestSta  is_train
0       1     1   0        0        6           0       31007      True
1       1     1   1        0        6           0       31104      True
2       1     1   2        0        6           0       31623      True
3       1     1   3        0        6           0       31102      True
4       1     1   4        0        6           0       31103      True

In [6]:
#Creating dataframes with test rows and training rows
train, test =CBS_2011_Hr[CBS_2011_Hr['is_train']==True], CBS_2011_Hr[CBS_2011_Hr['is_train']==False]
#show the number of observations for the test and training dataframes
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:', len(test))

Number of observations in the training data: 6967
Number of observations in the test data: 1678


In [7]:
#Create a list of the feature column's names
features=CBS_2011_Hr.columns[:6]
#View features
features

Index(['season', 'mnth', 'hr', 'holiday', 'weekday', 'workingday'], dtype='object')

In [8]:
#Converting each species ionto digits 
y_train=pd.factorize(train['BusiestSta'])[0]
#Viewing target
len(y_train), y_train.shape

(6967, (6967,))

In [9]:
#Converting each species ionto diigits 
y_test=pd.factorize(test['BusiestSta'])[0]
#Viewing target
len(y_test), y_test.shape

(1678, (1678,))

In [10]:
CBS_2011_Hr['BusiestSta'].unique()

array([31007, 31104, 31623, 31102, 31103, 31208, 31212, 31004, 31227,
       31204, 31201, 31111, 31200, 31217, 31219, 31602, 31228, 31620,
       31238, 31613, 31203, 31002, 31235, 31218, 31105, 31006, 31214,
       31611, 31112, 31009, 31619, 31101, 31220, 31106, 31108, 31213,
       31221, 31100, 31107, 31110, 31224, 31606, 31229, 31206, 31609,
       31223, 31202, 31617, 31622, 31607, 31109, 31216, 31215, 31400,
       31205, 31001, 31222, 31003, 31600, 31237, 31603, 31503, 31305,
       31608, 31008, 31624, 31605, 31302, 31236, 31300, 31401, 31301,
       31610, 31010, 31618, 31013, 31225, 31500, 31011, 31604, 31005,
       31207, 31303, 31601, 31000, 31209, 31504, 31616, 31226, 31014,
       31231, 31015, 31211, 31232, 31016, 31502, 31018, 31230, 31233,
       31501, 31012, 31402, 31621, 31261, 31017, 31239, 31244, 31241,
       31116, 31113, 31242, 31307, 31506, 31304], dtype=int64)

In [11]:
StaNum=CBS_2011_Hr['BusiestSta'].unique()

In [12]:
x_train=train[features]
x_train.shape

(6967, 6)

In [13]:
x_train

season  mnth  hr  holiday  weekday  workingday
0          1     1   0        0        6           0
1          1     1   1        0        6           0
2          1     1   2        0        6           0
3          1     1   3        0        6           0
4          1     1   4        0        6           0
...      ...   ...  ..      ...      ...         ...
8640       1    12  19        0        6           0
8641       1    12  20        0        6           0
8642       1    12  21        0        6           0
8643       1    12  22        0        6           0
8644       1    12  23        0        6           0

[6967 rows x 6 columns]

In [14]:
x_test=test[features]
x_test.shape

(1678, 6)

In [15]:
#Creating a random forest Classifier.
#clf = RandomForestClassifier(n_jobs=2,random_state=0)
clf = RandomForestClassifier(max_features=6, n_estimators=100)
#Training the classifier
clf.fit(x_train, y_train)

RandomForestClassifier(max_features=6)

In [16]:
clf.score(x_test, y_test)

0.010131108462455305

In [17]:
#Applying the trained Classifier to the test
clf.predict(x_test)

array([28, 28, 13, ...,  4,  4,  9], dtype=int64)

In [18]:
clf.predict_proba(test[features])[0:10]

array([[0.        , 0.01022222, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.35259524, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [19]:
#mapping names for the plants for each predicted plant class
preds=StaNum[clf.predict(test[features])]
#View the PREDICTED species for the firs five observations
preds[0:5]

array([31112, 31112, 31217, 31111, 31104], dtype=int64)

# Hyperparameter Tuning

In [20]:
from sklearn.model_selection import GridSearchCV
import numpy as np

max_features_range = np.arange(1,6,1)
n_estimators_range = np.arange(10,210,10)
param_grid =dict(max_features=max_features_range, n_estimators=n_estimators_range)

rf=RandomForestClassifier()
grid=GridSearchCV(estimator=rf, param_grid=param_grid, cv=5)

In [21]:
grid.fit(x_train, y_train)

C:\Users\Beto\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_features': array([1, 2, 3, 4, 5]),
                         'n_estimators': array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200])})

In [22]:
print("The best parameters are %s with score of %0.2f"%(grid.best_params_, grid.best_score_))

The best parameters are {'max_features': 5, 'n_estimators': 100} with score of 0.08
