In [1]:
#Loading scikit's random forest classifier library
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
#loading Pandas
import pandas as pd
#Loading numpy
import numpy as np
#Setting random seed
np.random.seed(0)

In [2]:
CBS_2011_Day=pd.read_csv("CBS_2011_TotalDay.csv")
CBS_2011_Day.head()

Unnamed: 0  instant  season  mnth  holiday  weekday  workingday  \
0           0      1.0     1.0   1.0      0.0      6.0         0.0   
1           1      2.0     1.0   1.0      0.0      0.0         0.0   
2           2      3.0     1.0   1.0      0.0      1.0         1.0   
3           3      4.0     1.0   1.0      0.0      2.0         1.0   
4           4      5.0     1.0   1.0      0.0      3.0         1.0   

   weathersit      temp     atemp       hum  windspeed  BusiestSta  
0         2.0  0.344167  0.363625  0.805833   0.160446       31228  
1         2.0  0.363478  0.353739  0.696087   0.248539       31602  
2         1.0  0.196364  0.189405  0.437273   0.248309       31101  
3         1.0  0.200000  0.212122  0.590435   0.160296       31101  
4         1.0  0.226957  0.229270  0.436957   0.186900       31104

In [3]:
del CBS_2011_Day['Unnamed: 0'] 
del CBS_2011_Day['instant'] 
# del CBS_2011_Day['season'] 
# del CBS_2011_Day['mnth'] 
# del CBS_2011_Day['hr'] 
# del CBS_2011_Day['holiday'] 
# del CBS_2011_Day['weekday'] 
# del CBS_2011_Day['workingday'] 
del CBS_2011_Day['weathersit'] 
del CBS_2011_Day['temp'] 
del CBS_2011_Day['atemp'] 
del CBS_2011_Day['hum'] 
del CBS_2011_Day['windspeed'] 

In [4]:
CBS_2011_Day.head()

season  mnth  holiday  weekday  workingday  BusiestSta
0     1.0   1.0      0.0      6.0         0.0       31228
1     1.0   1.0      0.0      0.0         0.0       31602
2     1.0   1.0      0.0      1.0         1.0       31101
3     1.0   1.0      0.0      2.0         1.0       31101
4     1.0   1.0      0.0      3.0         1.0       31104

In [5]:
#Creating Test and Train Data
CBS_2011_Day['is_train'] = np.random.uniform(0,1,len(CBS_2011_Day)) <= .80
#View the top 5 rows
CBS_2011_Day.head()

season  mnth  holiday  weekday  workingday  BusiestSta  is_train
0     1.0   1.0      0.0      6.0         0.0       31228      True
1     1.0   1.0      0.0      0.0         0.0       31602      True
2     1.0   1.0      0.0      1.0         1.0       31101      True
3     1.0   1.0      0.0      2.0         1.0       31101      True
4     1.0   1.0      0.0      3.0         1.0       31104      True

In [6]:
#Creating dataframes with test rows and training rows
train, test =CBS_2011_Day[CBS_2011_Day['is_train']==True], CBS_2011_Day[CBS_2011_Day['is_train']==False]
#show the number of observations for the test and training dataframes
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:', len(test))

Number of observations in the training data: 300
Number of observations in the test data: 65


In [7]:
#Create a list of the feature column's names
features=CBS_2011_Day.columns[:5]
#View features
features

Index(['season', 'mnth', 'holiday', 'weekday', 'workingday'], dtype='object')

In [8]:
#Converting each species ionto digits 
y_train=pd.factorize(train['BusiestSta'])[0]
#Viewing target
len(y_train), y_train.shape

(300, (300,))

In [9]:
#Converting each species ionto diigits 
y_test=pd.factorize(test['BusiestSta'])[0]
#Viewing target
len(y_test), y_test.shape

(65, (65,))

In [10]:
x_train=train[features]
x_train.shape

(300, 5)

In [11]:
x_test=test[features]
x_test.shape

(65, 5)

In [12]:
CBS_2011_Day['BusiestSta'].unique()

array([31228, 31602, 31101, 31104, 31201, 31200, 31110, 31219, 31217,
       31205, 31214, 31623], dtype=int64)

In [13]:
StaNum=CBS_2011_Day['BusiestSta'].unique()

In [23]:
#Creating a random forest Classifier.
#clf = RandomForestClassifier(n_jobs=2,random_state=0)
clf = RandomForestClassifier(max_features=1, n_estimators=10)
#Training the classifier
clf.fit(x_train, y_train)

RandomForestClassifier(max_features=1, n_estimators=10)

In [24]:
clf.score(x_test, y_test)

0.06153846153846154

In [16]:
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 5,
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 30,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [17]:
#Applying the trained Classifier to the test
clf.predict(x_test)

array([ 3,  3,  3,  2,  2,  3,  3,  4,  4,  4,  4,  4,  3,  3,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4, 11,  4, 11,  4,  4,  4,  4, 11,  4,  4,  8, 11,  6],
      dtype=int64)

In [18]:
clf.predict_proba(x_test)[0:10]

array([[0.22595238, 0.        , 0.        , 0.6215873 , 0.15246032,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.21507937, 0.        , 0.53281746, 0.25210317,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.26055556, 0.51111111, 0.22833333,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.59198413, 0.06230159, 0.05039683,
        0.29531746, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.64166667, 0.01111111, 0.34722222,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.26055556, 0.51111111, 0.22833333,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ,

In [19]:
#mapping names for the plants for each predicted plant class
preds=StaNum[clf.predict(test[features])]
#View the PREDICTED species for the firs five observations
preds[0:5]

array([31104, 31104, 31104, 31101, 31101], dtype=int64)

# Hyperparameter Tuning

In [20]:
from sklearn.model_selection import GridSearchCV
import numpy as np

max_features_range = np.arange(1,6,1)
n_estimators_range = np.arange(10,210,10)
param_grid =dict(max_features=max_features_range, n_estimators=n_estimators_range)

rf=RandomForestClassifier()
grid=GridSearchCV(estimator=rf, param_grid=param_grid, cv=5)

In [21]:
grid.fit(x_train, y_train)

C:\Users\Beto\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_features': array([1, 2, 3, 4, 5]),
                         'n_estimators': array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200])})

In [22]:
print("The best parameters are %s with score of %0.2f"%(grid.best_params_, grid.best_score_))

The best parameters are {'max_features': 1, 'n_estimators': 10} with score of 0.61
